version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: sparkifydb
      POSTGRES_USER: huyenvtk1
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume:
